### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by femikolade** [bmorgan5/fun_ofdm#1]
Hello,

I am trying to install this project on ubuntu 16.04 LTS. Everything runs fine until I run "make" command. Below is the response and error I get

Scanning dependencies of target transceiver
[ 96%] Building CXX object examples/CMakeFiles/transceiver.dir/simple_transceiver.cpp.o
/home/<path-to-fun_ofdm>/examples/simple_transceiver.cpp:3:34: fatal error: fun_ofdm/transmitter.h: No such file or directory
compilation terminated.
examples/CMakeFiles/transceiver.dir/build.make:62: recipe for target 'examples/CMakeFiles/transceiver.dir/simple_transceiver.cpp.o' failed
make[2]: *** [examples/CMakeFiles/transceiver.dir/simple_transceiver.cpp.o] Error 1
CMakeFiles/Makefile2:289: recipe for target 'examples/CMakeFiles/transceiver.dir/all' failed
make[1]: *** [examples/CMakeFiles/transceiver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

Please help.

**Comment by bmorgan5** [comment]
I'm sorry, I wasn't able to reproduce this error. It's possible that cmake has changed and isn't doing what it used to. Maybe try rolling your cmake back to v2.8?

**Comment by mohammad-shekarifard** [comment]
/home/mohammad/fun_ofdm/examples/simple_transceiver.cpp:3:34: fatal error: fun_ofdm/transmitter.h: No such file or directory
compilation terminated.
examples/CMakeFiles/transceiver.dir/build.make:62: recipe for target 'examples/CMakeFiles/transceiver.dir/simple_transceiver.cpp.o' failed
make[2]: *** [examples/CMakeFiles/transceiver.dir/simple_transceiver.cpp.o] Error 1
CMakeFiles/Makefile2:289: recipe for target 'examples/CMakeFiles/transceiver.dir/all' failed
make[1]: *** [examples/CMakeFiles/transceiver.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Hi, how can i fix this?
my camke version is :3.9

**Comment by bmorgan5** [comment]
Pushed an update to the build files in https://github.com/bmorgan5/fun_ofdm/commit/d4fe5334216da8eeb3703780d9629ce3b26e2a62. I'm going to close this issue. If you still have problems building after you pull the latest master, please let me know.
